# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculated.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(366, 542)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 81))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.num_0 = QtWidgets.QPushButton(self.centralwidget)
        self.num_0.setMinimumSize(QtCore.QSize(60, 60))
        self.num_0.setMaximumSize(QtCore.QSize(60, 60))
        self.num_0.setObjectName("num_0")
        self.gridLayout.addWidget(self.num_0, 0, 0, 1, 1)
        self.num_1 = QtWidgets.QPushButton(self.centralwidget)
        self.num_1.setMinimumSize(QtCore.QSize(60, 60))
        self.num_1.setMaximumSize(QtCore.QSize(60, 60))
        self.num_1.setObjectName("num_1")
        self.gridLayout.addWidget(self.num_1, 0, 1, 1, 1)
        self.num_3 = QtWidgets.QPushButton(self.centralwidget)
        self.num_3.setMinimumSize(QtCore.QSize(60, 60))
        self.num_3.setMaximumSize(QtCore.QSize(60, 60))
        self.num_3.setObjectName("num_3")
        self.gridLayout.addWidget(self.num_3, 0, 2, 1, 1)
        self.CE = QtWidgets.QPushButton(self.centralwidget)
        self.CE.setMinimumSize(QtCore.QSize(60, 60))
        self.CE.setMaximumSize(QtCore.QSize(60, 60))
        self.CE.setObjectName("CE")
        self.gridLayout.addWidget(self.CE, 0, 3, 1, 1)
        self.num_4 = QtWidgets.QPushButton(self.centralwidget)
        self.num_4.setMinimumSize(QtCore.QSize(60, 60))
        self.num_4.setMaximumSize(QtCore.QSize(60, 60))
        self.num_4.setObjectName("num_4")
        self.gridLayout.addWidget(self.num_4, 1, 0, 1, 1)
        self.num_5 = QtWidgets.QPushButton(self.centralwidget)
        self.num_5.setMinimumSize(QtCore.QSize(60, 60))
        self.num_5.setMaximumSize(QtCore.QSize(60, 60))
        self.num_5.setObjectName("num_5")
        self.gridLayout.addWidget(self.num_5, 1, 1, 1, 1)
        self.num_6 = QtWidgets.QPushButton(self.centralwidget)
        self.num_6.setMinimumSize(QtCore.QSize(60, 60))
        self.num_6.setMaximumSize(QtCore.QSize(60, 60))
        self.num_6.setObjectName("num_6")
        self.gridLayout.addWidget(self.num_6, 1, 2, 1, 1)
        self.op_mul = QtWidgets.QPushButton(self.centralwidget)
        self.op_mul.setMinimumSize(QtCore.QSize(60, 60))
        self.op_mul.setMaximumSize(QtCore.QSize(60, 60))
        self.op_mul.setObjectName("op_mul")
        self.gridLayout.addWidget(self.op_mul, 1, 3, 1, 1)
        self.num_7 = QtWidgets.QPushButton(self.centralwidget)
        self.num_7.setMinimumSize(QtCore.QSize(60, 60))
        self.num_7.setMaximumSize(QtCore.QSize(60, 60))
        self.num_7.setObjectName("num_7")
        self.gridLayout.addWidget(self.num_7, 2, 0, 1, 1)
        self.num_8 = QtWidgets.QPushButton(self.centralwidget)
        self.num_8.setMinimumSize(QtCore.QSize(60, 60))
        self.num_8.setMaximumSize(QtCore.QSize(60, 60))
        self.num_8.setObjectName("num_8")
        self.gridLayout.addWidget(self.num_8, 2, 1, 1, 1)
        self.num_9 = QtWidgets.QPushButton(self.centralwidget)
        self.num_9.setMinimumSize(QtCore.QSize(60, 60))
        self.num_9.setMaximumSize(QtCore.QSize(60, 60))
        self.num_9.setObjectName("num_9")
        self.gridLayout.addWidget(self.num_9, 2, 2, 1, 1)
        self.op_div = QtWidgets.QPushButton(self.centralwidget)
        self.op_div.setMinimumSize(QtCore.QSize(60, 60))
        self.op_div.setMaximumSize(QtCore.QSize(60, 60))
        self.op_div.setObjectName("op_div")
        self.gridLayout.addWidget(self.op_div, 2, 3, 1, 1)
        self.op_plus = QtWidgets.QPushButton(self.centralwidget)
        self.op_plus.setMinimumSize(QtCore.QSize(60, 60))
        self.op_plus.setMaximumSize(QtCore.QSize(60, 60))
        self.op_plus.setObjectName("op_plus")
        self.gridLayout.addWidget(self.op_plus, 3, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_13.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.op_sub = QtWidgets.QPushButton(self.centralwidget)
        self.op_sub.setMinimumSize(QtCore.QSize(60, 60))
        self.op_sub.setMaximumSize(QtCore.QSize(60, 60))
        self.op_sub.setObjectName("op_sub")
        self.gridLayout.addWidget(self.op_sub, 3, 2, 1, 1)
        self.op_equal = QtWidgets.QPushButton(self.centralwidget)
        self.op_equal.setMinimumSize(QtCore.QSize(60, 60))
        self.op_equal.setMaximumSize(QtCore.QSize(60, 60))
        self.op_equal.setObjectName("op_equal")
        self.gridLayout.addWidget(self.op_equal, 3, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 366, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.num_0.setText(_translate("MainWindow", "1"))
        self.num_1.setText(_translate("MainWindow", "2"))
        self.num_3.setText(_translate("MainWindow", "3"))
        self.CE.setText(_translate("MainWindow", "CE"))
        self.num_4.setText(_translate("MainWindow", "4"))
        self.num_5.setText(_translate("MainWindow", "5"))
        self.num_6.setText(_translate("MainWindow", "6"))
        self.op_mul.setText(_translate("MainWindow", "*"))
        self.num_7.setText(_translate("MainWindow", "7"))
        self.num_8.setText(_translate("MainWindow", "8"))
        self.num_9.setText(_translate("MainWindow", "9"))
        self.op_div.setText(_translate("MainWindow", "/"))
        self.op_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_13.setText(_translate("MainWindow", "0"))
        self.op_sub.setText(_translate("MainWindow", "-"))
        self.op_equal.setText(_translate("MainWindow", "="))

